### ISSUE TITLE
The modulizered version with Polymer 3.0 doesn't load the fonts

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/font-roboto-local#12]
### Description

The modulizered version with Polymer 3.0 doesn't load the fonts

### Expected outcome

Loading the fonts.

### Actual outcome

404 when loading the fonts.

<img width="1332" alt="screen shot 2018-05-12 at 15 12 08" src="https://user-images.githubusercontent.com/1007051/39957674-15b0655c-55f7-11e8-86d4-011d26b95ca1.png">

### Live Demo

https://jsbin.com/tegopevali/edit?html,output

### Steps to reproduce

Load the roboto.js and check the Developer Tools.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by brunowildhagen** [comment]
``` javascript
const $_documentContainer = document.createElement('template');
$_documentContainer.setAttribute('style', 'display: none;');

$_documentContainer.innerHTML = '<style>
@font-face {
font-family: "Roboto";
src: url(fonts/roboto/Roboto-Thin.ttf) format("truetype");
font-weight: 100;
font-style: normal;
}

```

I think the problem is the .ttf paths are relative to the main document, and not to the "roboto.js" file. You could use Document.currentScript, but it doesn't work with IE.

**Comment by e111077** [comment]
Document.currentScript always returns undefined in a module. We may have to rely on import.meta.url or this.importPath which relies on import.meta.

Problem is that import.meta is a syntax error on unsupported browsers and may require compilation

**Comment by abdonrd** [comment]
Closing and old issue.
