### ISSUE TITLE
This doesn't track PolymerElements/font-roboto.

### ISSUE THREAD

**Issue by Parakleta** [PolymerElements/font-roboto-local#2]
It's frustrating that this doesn't track the changes in PolymerElements/font-roboto, especially considering that the same committer updated both repositories on the same date and caused them to deviate.

Can you please add the mono fonts and update the version so this matches font-roboto.

**Comment by ebidel** [comment]
/sub. @azakus what are we doing with this?

**Comment by dfreedm** [comment]
Sure, that should be easy to add

**Comment by dfreedm** [comment]
Oh, yeah, there are no RobotoMono files in the source repo. That is why I didn't include them.

**Comment by dfreedm** [comment]
I should rebase off of google/fonts instead I suppose.
